/*******************************************************************************
 * Copyright (C) 2020, exense GmbH
 *
 * This file is part of STEP
 *
 * STEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * STEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with STEP.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package step.core.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.util.Objects;

/**
 * Marks the origin of an entity, i.e. what produced it. Generic on purpose: it is currently only used on plans
 * but is meant to be reusable for keywords and other entities.
 * <p>
 * In YAML this is written as a bare string as long as only {@link #getBy()} is set:
 * <pre>origin: ai</pre>
 * The object form is already accepted on read and is emitted as soon as any of the additional fields is set,
 * so extending this marker later does not require a schema change:
 * <pre>
 * origin:
 *   by: ai
 *   model: some-model
 *   timestamp: "2026-07-30T12:00:00Z"
 * </pre>
 *
 * @see EntityOriginSerializer
 * @see EntityOriginDeserializer
 */
@JsonSerialize(using = EntityOriginSerializer.class)
@JsonDeserialize(using = EntityOriginDeserializer.class)
public class EntityOrigin {

    /** The field name used in YAML descriptors. */
    public static final String YAML_FIELD = "origin";

    /** The key under which the origin is stored in the custom fields of the business object. */
    public static final String CUSTOM_FIELD = "origin";

    /** Value of {@link #getBy()} for entities generated by the AI agent. */
    public static final String BY_AI = "ai";

    private String by;
    private String model;
    private String timestamp;

    public EntityOrigin() {
    }

    public EntityOrigin(String by) {
        this.by = by;
    }

    public static EntityOrigin ai() {
        return new EntityOrigin(BY_AI);
    }

    public String getBy() {
        return by;
    }

    public void setBy(String by) {
        this.by = by;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    @JsonIgnore
    public boolean isAi() {
        return BY_AI.equals(by);
    }

    /**
     * @return true if this origin carries nothing but {@link #getBy()} and can therefore be written as a bare string
     */
    @JsonIgnore
    public boolean isPlainForm() {
        return model == null && timestamp == null;
    }

    @JsonIgnore
    public boolean isEmpty() {
        return by == null && model == null && timestamp == null;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof EntityOrigin)) {
            return false;
        }
        EntityOrigin other = (EntityOrigin) o;
        return Objects.equals(by, other.by) && Objects.equals(model, other.model)
                && Objects.equals(timestamp, other.timestamp);
    }

    @Override
    public int hashCode() {
        return Objects.hash(by, model, timestamp);
    }

    @Override
    public String toString() {
        return isPlainForm() ? String.valueOf(by)
                : "EntityOrigin{by=" + by + ", model=" + model + ", timestamp=" + timestamp + "}";
    }

    /**
     * Plain representation of the object form, used by the (de)serializers. It deliberately carries no custom
     * (de)serializer so that reading and writing the object form does not recurse into {@link EntityOrigin}'s own.
     */
    @JsonInclude(JsonInclude.Include.NON_NULL)
    static class Fields {

        public String by;
        public String model;
        public String timestamp;

        Fields() {
        }

        Fields(EntityOrigin origin) {
            this.by = origin.by;
            this.model = origin.model;
            this.timestamp = origin.timestamp;
        }

        EntityOrigin toEntityOrigin() {
            EntityOrigin origin = new EntityOrigin(by);
            origin.setModel(model);
            origin.setTimestamp(timestamp);
            return origin;
        }
    }
}
