controller.url=http://localhost:8080/
port=8080
#These cannot be disabled
plugins.StepControllerPlugin.enabled=true
plugins.MigrationExecutionPlugin.enabled=true
plugins.MigrationManagerPlugin.enabled=true
#These are required to get the non-disabled ones to work (in order of crashes i.e. dependencies)
plugins.VersionManagerPlugin.enabled=true
plugins.SchedulerPlugin.enabled=true
plugins.ControllerSettingPlugin.enabled=true
plugins.ObjectHookControllerPlugin.enabled=true
plugins.AutomationPackagePlugin.enabled=true
plugins.FunctionControllerPlugin.enabled=true
plugins.GridPlugin.enabled=true
plugins.AsyncTaskManagerPlugin.enabled=true
# The following are needed too as they cause runtime exceptions or other errors if absent
plugins.ScreenTemplatePlugin.enabled=true
plugins.PlanPlugin.enabled=true
plugins.TablePlugin.enabled=true
plugins.TableSettingsPlugin.enabled=true
# UI errors (only???)
plugins.BookmarkPlugin.enabled=true
plugins.ParameterManagerControllerPlugin.enabled=true
plugins.ExecutionPlugin.enabled=true
plugins.ExecutionTypeControllerPlugin.enabled=true
#Required functionality
plugins.CompositeFunctionTypeControllerPlugin.enabled=true
#Disable all other plugins for now
plugins.ArtifactRepositoryPlugin.enabled=false
plugins.AutomationPackageParameterPlugin.enabled=false
plugins.AutomationPackageRepositoriesPlugin.enabled=false
plugins.AutomationPackageSchedulerPlugin.enabled=false
plugins.BaseExecutionTypeControllerPlugin.enabled=false
plugins.DataPoolPlugin.enabled=false
plugins.EncryptionManagerDependencyPlugin.enabled=false
plugins.EntityLockingPlugin.enabled=false
plugins.ExportManagerPlugin.enabled=false
plugins.FunctionPackagePlugin.enabled=false
plugins.GeneralScriptFunctionControllerPlugin.enabled=true
plugins.InteractivePlugin.enabled=false
plugins.JMeterPlugin.enabled=true
plugins.LiveReportingControllerPlugin.enabled=false
plugins.MeasurementControllerPlugin.enabled=false
plugins.MigrationManagerTasksPlugin.enabled=false
plugins.MigrationTasksRegistrationPlugin.enabled=false
plugins.NodePlugin.enabled=true
plugins.QuotaManagerControllerPlugin.enabled=false
plugins.RawMeasurementsControllerPlugin.enabled=false
plugins.ReferenceFinderPlugin.enabled=false
plugins.RemoteCollectionPlugin.enabled=false
plugins.ResourceManagerControllerPlugin.enabled=false
plugins.ReportLayoutPlugin.enabled=false
plugins.ScriptEditorPlugin.enabled=true
plugins.StagingRepositoryPlugin.enabled=false
plugins.StreamingResourcesControllerPlugin.enabled=false
plugins.ThreadManagerControllerPlugin.enabled=false
plugins.TimeSeriesControllerPlugin.enabled=false
plugins.VersionProviderPlugin.enabled=false
plugins.ViewControllerPlugin.enabled=false
plugins.YamlEditorPlanPlugin.enabled=false
#datasource.db.type=step.core.collections.mongodb.MongoDBCollectionFactory
#datasource.db.collections=all
#datasource.db.properties.host=localhost
#datasource.db.properties.database=wtf
datasource.mem.type=step.core.collections.inmemory.InMemoryCollectionFactory
#datasource.mem.collections=controllerlogs
datasource.mem.collections=all
datasource.ap.type=step.ap_ide.CurrentlyOpenedAutomationPackageCollectionFactory
datasource.ap.collections=wtf,plans,functions,parameters
