/*******************************************************************************
 * Copyright (C) 2020, exense GmbH
 *
 * This file is part of STEP
 *
 * STEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * STEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with STEP.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package step.plugins.metrics.raw;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import step.core.GlobalContext;
import step.core.collections.Collection;
import step.core.collections.Document;
import step.core.collections.IndexField;
import step.core.collections.Order;
import step.core.entities.EntityConstants;
import step.core.plugins.AbstractControllerPlugin;
import step.core.plugins.Plugin;
import step.framework.server.tables.Table;
import step.framework.server.tables.TableRegistry;
import step.plugins.metrics.MetricsExecutionPlugin;
import step.plugins.metrics.ExecutionMetricSample;

import java.util.LinkedHashSet;
import java.util.List;

@Plugin
public class RawMetricsControllerPlugin extends AbstractControllerPlugin {

    private static final Logger logger = LoggerFactory.getLogger(RawMetricsControllerPlugin.class);

    private Collection<Document> measurementsCollection;
    private Collection<ExecutionMetricSample> metricSamplesCollection;

    @Override
    public void serverStart(GlobalContext context) throws Exception {

        measurementsCollection = context.getCollectionFactory().getCollection(EntityConstants.measurements, Document.class);
        MeasurementAccessor accessor = new MeasurementAccessor(measurementsCollection);
        context.put(MeasurementAccessor.class, accessor);

        TableRegistry tableRegistry = context.get(TableRegistry.class);
        tableRegistry.register(EntityConstants.measurements, new Table<>(measurementsCollection, null, false));

        metricSamplesCollection = context.getCollectionFactory().getCollection(EntityConstants.metricSamples, ExecutionMetricSample.class);
        MetricSampleAccessor metricsAccessor = new MetricSampleAccessor(metricSamplesCollection);
        context.put(MetricSampleAccessor.class, metricsAccessor);
        tableRegistry.register(EntityConstants.metricSamples, new Table<>(metricSamplesCollection, null, true));

        MetricsExecutionPlugin.registerSamplesHandlers(new RawMetricSamplesHandler(accessor, metricsAccessor));

        context.getServiceRegistrationCallback().registerService(RawSamplesServices.class);
    }

    @Override
    public void initializeData(GlobalContext context) throws Exception {
        IndexField eidIndex = new IndexField(MetricsExecutionPlugin.ATTRIBUTE_EXECUTION_ID, Order.ASC, String.class);
        IndexField beginIndex = new IndexField(MetricsExecutionPlugin.BEGIN, Order.ASC, Integer.class);
        IndexField typeIndex = new IndexField(MetricsExecutionPlugin.TYPE, Order.ASC, String.class);
        IndexField planIndex = new IndexField(MetricsExecutionPlugin.PLAN_ID, Order.ASC, String.class);
        IndexField taskIndex = new IndexField(MetricsExecutionPlugin.TASK_ID, Order.ASC, String.class);
        IndexField rnIdIndex = new IndexField(MetricsExecutionPlugin.RN_ID, Order.ASC, String.class);
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(eidIndex, beginIndex)));
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(eidIndex, typeIndex, beginIndex)));
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(planIndex, beginIndex)));
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(taskIndex, beginIndex)));
        measurementsCollection.createOrUpdateIndex(beginIndex);
        measurementsCollection.createOrUpdateIndex(rnIdIndex);

        //required for node details showing metrics generated by a specific report node
        metricSamplesCollection.createOrUpdateIndex(rnIdIndex);
        //required for housekeeping
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(eidIndex)));
    }
}
