{"keywords":[{"name":"GetFromQueue","type":"LOCAL"},
{"name":"PutToQueue","type":"LOCAL"},
{"name":"errorTest","type":"LOCAL"},
{"name":"echo","type":"LOCAL"},
{"name":"echo","type":"REMOTE","selectionPatterns":{"type":"QFTEST"},"activationExpression":"profile=='ECHO_QFT'"},
{"name":"SleepQFT","type":"REMOTE","selectionPatterns":{"type":"QFTEST"}},
{"name":"Sleep","type":"LOCAL","hasSchema":"true"},
{"name":"Sleep","type":"LOCAL","hasSchema":"false","activationExpression":"TestWithoutSchema==true"},
{"name":"ErrorEcho","type":"REMOTE","selectionPatterns":{"type":"QFTEST"}},
{"name":"TransactionEcho","type":"REMOTE","selectionPatterns":{"type":"QFTEST"}},
{"name":"Sikuli_Echo","type":"REMOTE","selectionPatterns":{"type":"SIKULI"}},
{"name":"Sikuli_Test","type":"REMOTE","selectionPatterns":{"type":"SIKULI"}}
]}