{
"executionParameters":[
  {"id":"profile","options":["DEFAULT"]}
],
"executionTable":[
  {"id":"executionParameters.customParameters.profile","label":"Profile"}
],
"functionTable":[
                  {"id":"version","label":"Version"}
]
}