/*******************************************************************************
 * Copyright (C) 2020, exense GmbH
 *
 * This file is part of STEP
 *
 * STEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * STEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with STEP.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package step.plugins.measurements.raw;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import step.core.GlobalContext;
import step.core.collections.Collection;
import step.core.collections.Document;
import step.core.collections.IndexField;
import step.core.collections.Order;
import step.core.entities.EntityConstants;
import step.core.plugins.AbstractControllerPlugin;
import step.core.plugins.Plugin;
import step.framework.server.tables.Table;
import step.framework.server.tables.TableRegistry;
import step.plugins.measurements.MeasurementPlugin;
import step.plugins.measurements.MetricMeasurement;

import java.util.LinkedHashSet;
import java.util.List;

@Plugin
public class RawMeasurementsControllerPlugin extends AbstractControllerPlugin {

    private static final Logger logger = LoggerFactory.getLogger(RawMeasurementsControllerPlugin.class);

    private Collection<Document> measurementsCollection;
    private Collection<MetricMeasurement> metricsCollection;

    @Override
    public void serverStart(GlobalContext context) throws Exception {

        measurementsCollection = context.getCollectionFactory().getCollection(EntityConstants.measurements, Document.class);
        MeasurementAccessor accessor = new MeasurementAccessor(measurementsCollection);
        context.put(MeasurementAccessor.class, accessor);

        TableRegistry tableRegistry = context.get(TableRegistry.class);
        tableRegistry.register(EntityConstants.measurements, new Table<>(measurementsCollection, null, false));

        metricsCollection = context.getCollectionFactory().getCollection(EntityConstants.measurements, MetricMeasurement.class);
        MetricAccessor metricsAccessor = new MetricAccessor(metricsCollection);
        context.put(MetricAccessor.class, metricsAccessor);
        tableRegistry.register(EntityConstants.metrics, new Table<>(metricsCollection, null, true));

        MeasurementPlugin.registerMeasurementHandlers(new RawMeasurementsHandler(accessor, metricsAccessor));
    }

    @Override
    public void serverStop(GlobalContext context) {
    }

    @Override
    public void initializeData(GlobalContext context) throws Exception {
        IndexField eidIndex = new IndexField(MeasurementPlugin.ATTRIBUTE_EXECUTION_ID, Order.ASC, String.class);
        IndexField beginIndex = new IndexField(MeasurementPlugin.BEGIN, Order.ASC, Integer.class);
        IndexField typeIndex = new IndexField(MeasurementPlugin.TYPE, Order.ASC, String.class);
        IndexField planIndex = new IndexField(MeasurementPlugin.PLAN_ID, Order.ASC, String.class);
        IndexField taskIndex = new IndexField(MeasurementPlugin.TASK_ID, Order.ASC, String.class);
        IndexField rnIdIndex = new IndexField(MeasurementPlugin.RN_ID, Order.ASC, String.class);
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(eidIndex, beginIndex)));
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(eidIndex, typeIndex, beginIndex)));
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(planIndex, beginIndex)));
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(taskIndex, beginIndex)));
        measurementsCollection.createOrUpdateIndex(beginIndex);
        measurementsCollection.createOrUpdateIndex(rnIdIndex);

        //required for node details showing metrics generated by a specific report node
        metricsCollection.createOrUpdateIndex(rnIdIndex);
        //required for housekeeping
        measurementsCollection.createOrUpdateCompoundIndex(new LinkedHashSet<>(List.of(eidIndex)));
    }
}
