{
"executionParameters":[
  {"id":"usr","options":["ex3cv"]}
],
"executionTable":[
  {"id":"executionParameters.customParameters.profile","label":"Profile"}
],
"functionTable":[
  {"id":"attributes.name","label":"Name","type":"TEXT"}
],
"artefactTable":[
  {"id":"attributes.name","label":"Name","type":"TEXT"}
]
}