{
"executionParameters":[
  {"id":"profile","options":["DEFAULT"]}
],
"executionTable":[
  {"id":"executionParameters.customParameters.profile","label":"Profile"}
],
"functionTable":[
	{"id":"attributes.name","label":"Name","type":"TEXT"},
    {"id":"attributes.version","label":"Version","type":"TEXT"}
]
}