{
"executionParameters":[
  {"id":"env","options":["TEST","PROD"],"label":"Environment"}
],
"executionTable":[
  {"id":"executionParameters.customParameters.env","label":"Environment"}
],
"functionTable":[
  {"id":"name","label":"Name","type":"TEXT"}
],
"artefactTable":[
  {"id":"attributes.name","label":"Name","type":"TEXT"}
]
}