{
"executionParameters":[
  {"id":"env","options":["TEST","PROD"],"label":"Environment"}
],
"executionTable":[
  {"id":"executionParameters.customParameters.profile","label":"Profile"}
],
"functionTable":[
  {"id":"app","label":"Application","options":["App1","App2"]},
  {"id":"name","label":"Name","type":"TEXT"}
],
"artefactTable":[
  {"id":"attributes.name","label":"Name","type":"TEXT"},
  {"id":"attributes.app","label":"Application","type":"TEXT"}
]
}